### ISSUE TITLE
attention map and gt mask matching

### ISSUE THREAD

**Issue by neverUseThisName** [JStehouwer/FFD_CVPR2020#1]
Hi, thanks for your work. I have a small question.
The attention map size is 19x19, but the gt mask (diff image) is 299x299. Are they matched by downsampling gt mask?

**Comment by JStehouwer** [comment]
Yes. The gt mask is 299x299, but is converted to greyscale, resized to 19x19, and thresholded (using a threshold value of 0.1 assuming an image is in the range [0,1]) so that it is binary.
