### ISSUE TITLE
Could you provide an initial model?

### ISSUE THREAD

**Issue by Lin427** [JStehouwer/FFD_CVPR2020#2]
Hi, I'm very interested in your work. Could you provide a simple initial model? I want to run the program to see the effect. Extremely grateful！

**Comment by JStehouwer** [comment]
Hi Lin427, thanks for your interest in our work! I contacted the guy that has the saved models, and once he gets back to me, I will be posting it under the releases tab. I will post here again once that has been done.

**Comment by Lin427** [comment]
Okay, thank you very much!

**Comment by JStehouwer** [comment]
I have now uploaded an example MAM model to the releases page.
