### ISSUE TITLE
Would you please write a simple tutuorial on how to reproduce the results in the paper?

### ISSUE THREAD

**Issue by CoinCheung** [JStehouwer/FFD_CVPR2020#3]
Hi, 

Thanks for releasing this !!!

Would you please add a few lines on the pipeline of how to reproduce the results in the paper?

**Comment by JStehouwer** [comment]
Hi CoinCheung!

Yeah, I'm in the process of uploading most of our models that were used in the paper to the "Releases" tab. I can add the information you requested to the readme.

**Comment by CoinCheung** [comment]
Thanks for replying !!! 
Will you also release the pretrained models that achieves the results reported in the paper ?

**Comment by JStehouwer** [comment]
I just replied to another issue for this repo [https://github.com/JStehouwer/FFD_CVPR2020/issues/5](https://github.com/JStehouwer/FFD_CVPR2020/issues/5) that is related.

I hope to get these done in the near future, but this is dependent upon my having access to a GPU machine to verify the train/test process works as expected.
