### ISSUE TITLE
Question about mask images in dataset

### ISSUE THREAD

**Issue by piddnad** [JStehouwer/FFD_CVPR2020#7]
Thank you for releasing the code and the DFFD dataset!

I noticed that in the "faceapp" part of the dataset, there is a ground-truth manipulation masks image for each fake image. How are these mask images generated?

The paper mentioned that the ground-truth manipulation mask were calculated by source images and fake images, but I still did not understand how. 

Thank you for answering my question. :)

**Comment by JStehouwer** [comment]
Hi piddnad!

Thanks for the interest in our work! I hope it can help to inspire your own.

For the FaceApp images, we used an automated script to upload a face image from an Android smartphone to the app and then randomly manipulate the face using the options in FaceApp.

These manipulated images were then downloaded and could be used with the original image to compute the manipulation masks.

**Comment by piddnad** [comment]
> These manipulated images were then downloaded and could be used with the original image to compute the manipulation masks.

I understand. Thank you for your answers!
